### ISSUE TITLE
Implement tournament registrations

### ISSUE THREAD

**Issue by imprima** [axuno/ClubSite#2]
Implement pages for registering for a tournament, and manage registrations

**Comment by axunonb** [comment]
* Table structure for table `Club_TournamentRegistration` has been changed
* There can be any number of `TournamtPage`s which define a tournament
* For each tournament date defined in a `TournamtPage` separate (independent) registrations are possible
* People registering a team will receive an email confirmation
* A registration confirmation will be sent to the defined club email address
* Users, who have permission `Piranha.Manager.Permission.Pages` can edit tournament registrations, set/unset status `IsStandByRegistration` or enter the cancellation date for a registration
