### ISSUE TITLE
Create custom page or content block for "Training"

### ISSUE THREAD

**Issue by imprima** [axuno/ClubSite#4]
![Page_Training](https://user-images.githubusercontent.com/64682890/104661002-f1320580-56c7-11eb-884e-bee56a9c832e.png)

**Comment by imprima** [comment]
Currently, the gray background color of the training units is realized with custom HTML entered in the editor:

```Html
<article class="h-100">
    <div class="alert alert-light h-100">
        <!-- Formatted HTML content goes here -->
    </div>
</article>
```
The result looks like so:
![image](https://user-images.githubusercontent.com/64682890/209231490-09bfc6c4-1b77-4e6a-b72c-7f73f9b040eb.png)

The custom HTML is **not visible** in the WYSIWYG view of the editor, with the risk of being deleted by mistake. This leads to missing background.
![image](https://user-images.githubusercontent.com/64682890/209231826-68da7eb3-e2b1-4361-adb0-d280f89017ae.png)

A custom `Content` block that allows you to easily set the background color would be handy.

**Comment by axunonb** [comment]
So, something like this?
## Editor:
![image](https://user-images.githubusercontent.com/10255664/209240785-ac0aade5-e28d-45d4-b1ce-98d9e9d6ba4e.png)
## Result:
![image](https://user-images.githubusercontent.com/10255664/209240935-f09c5bec-1d06-459c-9754-d1e2bd4c7c4d.png)

**Comment by axunonb** [comment]
Btw. There is an Emoji database which also includes symbols/icons: https://emojidb.org/
These emojis can be copied and inserted in the content editor
